import type { Metadata } from "next";
import Link from "next/link";
import LegalShell, { Note, Section } from "../components/LegalShell";
import { SITE } from "../lib/calculators";
import { LEGAL_CONTACT_EMAIL, LEGAL_UPDATED_LABEL } from "../lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How ShouldIFinance handles your information. Calculator inputs are processed in your browser and never sent to us. No analytics, no tracking, no accounts.",
  alternates: { canonical: `${SITE}/privacy` },
  openGraph: {
    type: "website",
    siteName: "ShouldIFinance",
    url: `${SITE}/privacy`,
    title: "Privacy Policy | ShouldIFinance",
    description: "Calculator inputs are processed in your browser and never sent to us.",
  },
};

export default function PrivacyPolicy() {
  return (
    <LegalShell
      eyebrow="Privacy"
      title="Privacy Policy"
      intro="The short version: the calculators run inside your browser, the numbers you type never reach us, and there is nothing to sign up for. The rest of this page explains that in detail and tells you what would change if that ever stops being true."
      current="/privacy"
    >
      <Note tone="green">
        <strong>The one thing worth knowing.</strong> Every calculator on this site computes in your
        own browser. Your income, balances, debts and the rest are held in the page while you have it
        open and are discarded when you close the tab. They are not sent to a server, not written to
        your device, and not seen by us. You can confirm this yourself: open your browser&apos;s
        network tools, fill in a calculator, and watch that no request is made.
      </Note>

      <Section id="who-we-are" heading="1. Who this policy covers">
        This policy applies to the website at shouldifinance.com (the &ldquo;Site&rdquo;), which is an
        independent educational project offering free financial calculators. It describes what
        information the Site handles and what it does not. It does not cover any other website,
        including sites you reach by following a link from here.
      </Section>

      <Section id="calculator-inputs" heading="2. Calculator inputs are never transmitted">
        <p>
          The calculators are client-side programs. When you type a purchase price, a salary, a loan
          balance or any other figure, that value is held in your browser&apos;s memory and used to
          compute the result shown on screen. It is not transmitted to us or to anyone else, not
          stored in a database, and not retained after you close or reload the page.
        </p>
        <p>
          The Site has no accounts, no sign-up, no login and no forms that submit anywhere. There is
          no mechanism by which a figure you enter could reach us, because none was built.
        </p>
      </Section>

      <Section id="what-we-dont-collect" heading="3. What the Site does not collect">
        <p>As of {LEGAL_UPDATED_LABEL}, the Site does not:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>collect names, email addresses, phone numbers or postal addresses;</li>
          <li>ask for or process financial account numbers, Social Security numbers or credit information;</li>
          <li>use analytics or measurement tools of any kind — there is no Google Analytics, Tag Manager, Plausible, Fathom, PostHog, Mixpanel, Hotjar, Meta pixel or equivalent;</li>
          <li>use advertising networks, retargeting pixels or data brokers;</li>
          <li>embed third-party scripts, iframes, chat widgets, video players or social media embeds;</li>
          <li>write cookies, <code className="text-xs">localStorage</code>, <code className="text-xs">sessionStorage</code> or any other data to your device;</li>
          <li>build profiles of visitors, or sell or share personal information with anyone.</li>
        </ul>
        <p>
          Web fonts are served from this Site&apos;s own servers rather than loaded from a font
          provider, so viewing a page does not reveal your visit to a third party in that way either.
        </p>
      </Section>

      <Section id="hosting-and-logs" heading="4. Hosting and server logs">
        <p>
          The Site is delivered by a third-party hosting provider. Like essentially all web hosts,
          that provider processes the technical information your browser sends in order to deliver a
          page: your IP address, the page requested, the date and time, your browser and operating
          system, and the referring page if there is one. This is ordinary server-log data, it is
          generated by the act of visiting any website, and it is handled by the hosting provider
          under its own terms rather than by us.
        </p>
        <p>
          We do not use that log data to identify visitors, we do not combine it with anything else,
          and we do not draw on it for marketing. The hosting provider may also set strictly
          necessary operational cookies — for example to route requests or manage caching — which
          serve the delivery of the page rather than any tracking purpose.
        </p>
        <Note>
          <strong>To be completed before publication.</strong> The hosting provider must be named
          here, with a link to its privacy documentation, and its actual log-retention period stated.
          At the time of drafting, the domain was still served by a previous host that sets its own
          cookies, which this Site does not. Confirm which platform is live and restate this section
          to match it.
        </Note>
      </Section>

      <Section id="cookies" heading="5. Cookies">
        <p>
          This Site sets no cookies of its own. It has no cookie banner because, as built, it has
          nothing to ask consent for beyond the strictly necessary operational cookies a host may use
          to deliver the page, which do not require consent in most jurisdictions.
        </p>
        <p>
          If advertising is added in future, that will change — see section 6. Any such change will
          be reflected here, with the date at the top of this page updated, before the change goes
          live.
        </p>
      </Section>

      <Section id="not-yet-in-use" heading="6. Advertising and email — not in use today">
        <Note>
          <strong>Nothing in this section is active.</strong> There is no advertising on this Site
          and no email collection of any kind today. This section exists so you can see what would
          change, not to describe something already happening.
        </Note>
        <p>
          The Site may in future carry advertising or offer an email newsletter. Rather than publish
          terms for things that do not exist — which would describe the Site inaccurately — this
          policy will be rewritten and re-dated <em>before</em> either is introduced. When that
          happens, expect the following to be addressed:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong>Advertising.</strong> Ad networks typically set their own cookies or similar
            identifiers and may collect IP address, device and browsing data for ad selection and
            measurement. The networks used would be named, their privacy policies linked, and a
            consent mechanism added where the law requires one. Under CCPA, some ad arrangements
            count as &ldquo;sharing&rdquo; personal information for cross-context behavioural
            advertising, which would require a clear opt-out.
          </li>
          <li>
            <strong>Email.</strong> A newsletter would collect the address you give and nothing you
            do not volunteer. It would be opt-in, every message would carry an unsubscribe link, and
            the address would not be sold or rented.
          </li>
        </ul>
        <p>
          Until this section says otherwise, neither applies. If you are reading this and the Site is
          showing you adverts, this policy is out of date and should not be relied on — please tell
          us at{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-green-700 underline">
            {LEGAL_CONTACT_EMAIL}
          </a>
          .
        </p>
      </Section>

      <Section id="third-parties" heading="7. Links to other sites">
        <p>
          The Site links to external resources — government and regulatory sources such as the IRS,
          and social media profiles in the footer. Following a link takes you to a site we do not
          control, with its own privacy practices. This policy stops at our boundary. We are not
          responsible for what other operators do with your information, and you should read their
          policies before relying on them.
        </p>
      </Section>

      <Section id="retention" heading="8. Data retention">
        <p>
          We retain no personal information, because we collect none. There is no database of
          visitors, no stored calculator history and no archive to request deletion from. Hosting
          logs are retained by the hosting provider for its own operational period, described in
          section 4.
        </p>
      </Section>

      <Section id="security" heading="9. Security">
        <p>
          The Site is served over HTTPS. Because the figures you enter never leave your browser, the
          most sensitive information involved in using this Site is never in transit and never at
          rest on our side — which is a stronger protection than any security measure applied to
          stored data. No method of transmission over the internet is completely secure, and no
          assurance of absolute security is given.
        </p>
      </Section>

      <Section id="your-rights" heading="10. Your rights (CCPA and GDPR)">
        <p>
          Depending on where you live, you may have rights over personal information a business holds
          about you — including the right to know what is held, to obtain a copy, to correct it, to
          have it deleted, to opt out of its sale or sharing, and not to be discriminated against for
          exercising any of these.
        </p>
        <p>
          <strong>California residents (CCPA/CPRA).</strong> We do not collect, sell or share
          personal information as those terms are defined by California law, and we do not use
          personal information for cross-context behavioural advertising. There is therefore nothing
          for us to disclose, delete or opt you out of. If that changes — see section 6 — this
          section will be rewritten with the disclosures and the opt-out mechanism California law
          requires.
        </p>
        <p>
          <strong>UK and EU residents (UK GDPR / EU GDPR).</strong> We are not a controller of any
          personal data about you, because we hold none. Server-log processing by the hosting
          provider is carried out on the basis of legitimate interests in delivering and securing the
          Site. You retain your rights of access, rectification, erasure, restriction, portability
          and objection, and the right to complain to your supervisory authority — in the UK, the
          Information Commissioner&apos;s Office.
        </p>
        <p>
          To exercise any right, or to ask what is held about you, write to{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-green-700 underline">
            {LEGAL_CONTACT_EMAIL}
          </a>
          . We will respond within the period the applicable law requires. In most cases the honest
          answer will be that we hold nothing.
        </p>
      </Section>

      <Section id="children" heading="11. Children&rsquo;s privacy">
        <p>
          The Site is intended for adults making financial decisions. It is not directed to children
          under 13, and we do not knowingly collect personal information from children under 13 —
          indeed we do not knowingly collect personal information from anyone, of any age, as
          described above. If you believe a child has provided personal information to us, contact{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-green-700 underline">
            {LEGAL_CONTACT_EMAIL}
          </a>{" "}
          and we will take appropriate steps.
        </p>
      </Section>

      <Section id="changes" heading="12. Changes to this policy">
        <p>
          This policy may be revised as the Site changes. The date at the top of the page shows when
          it was last altered. Material changes — particularly the introduction of advertising or
          email collection — will be reflected here before they take effect, not after.
        </p>
      </Section>

      <Section id="contact" heading="13. Contact">
        <p>
          Questions about this policy, or about privacy on this Site, can be sent to{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-green-700 underline">
            {LEGAL_CONTACT_EMAIL}
          </a>
          .
        </p>
        <p>
          See also the{" "}
          <Link href="/terms" className="text-green-700 underline">
            Terms of Use
          </Link>{" "}
          and the{" "}
          <Link href="/disclaimer" className="text-green-700 underline">
            Disclaimer
          </Link>
          , which explain the limits of what this Site is and what it can be relied on for.
        </p>
      </Section>
    </LegalShell>
  );
}
